# agent.toml: Operational configuration for the Project Architect

[core]
name = "ProjectArchitect"
version = "1.0.0"

[capabilities]
# Defines the tools this agent is allowed to use.
tools = ["read_directory_structure"]

[execution]
mode = "single_run"
entrypoint = "main_prompt"
prompt_template_file = "agent.md"

[logging]
level = "INFO"
file = "/var/log/agents/architect.log"