# agent.toml: Operational configuration for the Lead Auditor

[core]
name = "LeadAuditor"
version = "1.0.0"

[capabilities]
# This agent doesn't need file system access, only text processing.
tools = ["text_analysis"]

[execution]
mode = "single_run"
entrypoint = "main_prompt"
prompt_template_file = "agent.md"

[logging]
level = "INFO"
file = "/var/log/agents/auditor.log"