# Kong API Gateway Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: houston-oil-airs
data:
  kong.yml: |
    _format_version: "3.0"
    services:
    - name: houston-backend
      url: http://houston-backend-service:3001
      routes:
      - name: api-route
        paths:
        - /api
        strip_path: true
        plugins:
        - name: rate-limiting
          config:
            minute: 100
            hour: 1000
        - name: cors
          config:
            origins:
            - "https://houstonoilairs.org"
            - "https://www.houstonoilairs.org"
    - name: houston-frontend
      url: http://houston-frontend-service:80
      routes:
      - name: frontend-route
        paths:
        - /
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
  namespace: houston-oil-airs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kong-gateway
  template:
    metadata:
      labels:
        app: kong-gateway
    spec:
      containers:
      - name: kong
        image: kong:3.4
        ports:
        - containerPort: 8000
        - containerPort: 8001
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_DECLARATIVE_CONFIG
          value: "/kong/kong.yml"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"
        volumeMounts:
        - name: kong-config
          mountPath: /kong
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: kong-config
        configMap:
          name: kong-config
---
apiVersion: v1
kind: Service
metadata:
  name: kong-gateway-service
  namespace: houston-oil-airs
spec:
  selector:
    app: kong-gateway
  ports:
  - name: proxy
    port: 8000
    targetPort: 8000
  - name: admin
    port: 8001
    targetPort: 8001
  type: ClusterIP