# ServiceMonitor for Prometheus to scrape metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: houston-backend-metrics
  namespace: houston-oil-airs
  labels:
    app: houston-backend
spec:
  selector:
    matchLabels:
      app: houston-backend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
# Grafana Dashboard ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: houston-dashboard
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  houston-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Houston Oil Airs Dashboard",
        "tags": ["houston"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Request Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(app_requests_total[5m])",
                "legendFormat": "{{route}}"
              }
            ]
          },
          {
            "id": 2,
            "title": "Response Time",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(app_route_duration_seconds_bucket[5m]))",
                "legendFormat": "95th percentile"
              }
            ]
          },
          {
            "id": 3,
            "title": "Error Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(app_route_errors_total[5m])",
                "legendFormat": "{{route}}"
              }
            ]
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "5s"
      }
    }
---
# AlertManager rules
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: houston-alerts
  namespace: houston-oil-airs
spec:
  groups:
  - name: houston.rules
    rules:
    - alert: HighErrorRate
      expr: rate(app_route_errors_total[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value }} errors per second"
    - alert: HighResponseTime
      expr: histogram_quantile(0.95, rate(app_route_duration_seconds_bucket[5m])) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High response time detected"
        description: "95th percentile response time is {{ $value }} seconds"