# agent.toml: Operational configuration for the Code Inspector

[core]
name = "CodeInspector"
version = "1.0.0"

[capabilities]
tools = ["read_file_content"]

[execution]
mode = "single_run"
entrypoint = "main_prompt"
prompt_template_file = "agent.md"

[logging]
level = "INFO"
file = "/var/log/agents/inspector.log"