apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- replica-patch.yaml
- resource-patch.yaml

images:
- name: ghcr.io/senpai-sama7/houston-oil-airs/frontend
  newTag: latest
- name: ghcr.io/senpai-sama7/houston-oil-airs/backend
  newTag: latest

commonLabels:
  environment: production