name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, copilot/** ]
    paths:
      - 'platform/community/portal/**'
      - '.github/workflows/ci-cd.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'platform/community/portal/**'

env:
  NODE_VERSION: '20.x'
  WORKING_DIR: platform/community/portal

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.WORKING_DIR }}/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run ESLint
        run: npm run lint
        working-directory: ${{ env.WORKING_DIR }}

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.WORKING_DIR }}/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run TypeScript type checking
        run: npm run type-check
        working-directory: ${{ env.WORKING_DIR }}

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint, type-check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.WORKING_DIR }}/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIR }}

      - name: Build Next.js application
        run: npm run build
        working-directory: ${{ env.WORKING_DIR }}
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: ${{ env.WORKING_DIR }}/.next
          retention-days: 7

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [lint, type-check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.WORKING_DIR }}/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run unit tests
        run: npm test
        working-directory: ${{ env.WORKING_DIR }}
        continue-on-error: true

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.WORKING_DIR }}/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run npm audit
        run: npm audit --audit-level=moderate
        working-directory: ${{ env.WORKING_DIR }}
        continue-on-error: true

      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=high --file=${{ env.WORKING_DIR }}/package.json

  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.WORKING_DIR }}/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIR }}

      - name: Build for export
        run: npm run build
        working-directory: ${{ env.WORKING_DIR }}
        env:
          GITHUB_PAGES: true

      - name: Comment PR with preview info
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview build completed successfully!\n\nCommit: ${{ github.sha }}'
            })

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, test, security]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{ env.WORKING_DIR }}/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKING_DIR }}

      - name: Build for GitHub Pages
        run: npm run build
        working-directory: ${{ env.WORKING_DIR }}
        env:
          GITHUB_PAGES: true
          NEXT_TELEMETRY_DISABLED: 1

      - name: Export static site
        run: |
          cd ${{ env.WORKING_DIR }}
          npx next export -o out

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.WORKING_DIR }}/out
          publish_branch: gh-pages
          cname: houstonoilairs.org
