name: CI

on:
  push:
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: frontend
        run: |
          npm ci
          npx playwright install-deps
          npx playwright install
      - name: Lint
        working-directory: frontend
        run: npm run lint
      - name: Unit tests
        working-directory: frontend
        run: npm run test:unit
      - name: E2E tests
        working-directory: frontend
        run: npm test
      - name: Audit
        working-directory: frontend
        run: npm audit --audit-level=high

  backend-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: backend/node-server
        run: npm ci
      - name: Lint
        working-directory: backend/node-server
        run: npm run lint
      - name: Test
        working-directory: backend/node-server
        run: npm test

  backend-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Test
        working-directory: backend/java-services
        run: mvn -B test

  backend-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: backend/cpp-engine
        run: |
          cmake -S . -B build
          cmake --build build
